using System.Diagnostics.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;

namespace Naratteu.StrongDuck.Tests;

public class DuckTypeGeneratorTests
{
    /// <summary>호출지점만 보고 어댑터를 만들어낸다. 선언해둘 게 따로 없다.</summary>
    [Fact]
    public async Task GeneratesFromCallSites()
    {
        var test = Test(/*lang=C#*/"""
            interface IDuck { string Quack(); }
            class Chick { public string Quack() => "chick"; }
            class Dog { public string Quack() => "dog"; }

            class Use
            {
                static IDuck A() => IDuck.From(new Chick());
                static IDuck B() => new Dog().ToDuck<IDuck>();
            }
            """);

        Expect(test, "__Duck_IDuck__Chick.g.cs", """
            // <auto-generated/>
            #nullable enable
            namespace Naratteu.StrongDuck.Generated
            {
                internal sealed class __Duck_IDuck__Chick : global::IDuck
                {
                    private readonly global::Chick t;
                    public __Duck_IDuck__Chick(global::Chick t) => this.t = t;

                    string global::IDuck.Quack() => t.Quack();
                }
            }
            """);

        Expect(test, "__Duck_IDuck__Dog.g.cs", """
            // <auto-generated/>
            #nullable enable
            namespace Naratteu.StrongDuck.Generated
            {
                internal sealed class __Duck_IDuck__Dog : global::IDuck
                {
                    private readonly global::Dog t;
                    public __Duck_IDuck__Dog(global::Dog t) => this.t = t;

                    string global::IDuck.Quack() => t.Quack();
                }
            }
            """);

        Expect(test, "__Duck_IDuck_Ext.g.cs", """
            // <auto-generated/>
            #nullable enable

            /// <summary>global::IDuck 의 덕타이핑 진입점.</summary>
            internal static class __Duck_IDuck_Ext
            {
                extension(global::IDuck)
                {
                    public static global::IDuck From(global::Chick t) => new global::Naratteu.StrongDuck.Generated.__Duck_IDuck__Chick(t);
                    public static global::IDuck From(global::Dog t) => new global::Naratteu.StrongDuck.Generated.__Duck_IDuck__Dog(t);
                }

                public static global::IDuck ToDuck<_>(this global::Chick t) where _ : global::IDuck => new global::Naratteu.StrongDuck.Generated.__Duck_IDuck__Chick(t);
                public static global::IDuck ToDuck<_>(this global::Dog t) where _ : global::IDuck => new global::Naratteu.StrongDuck.Generated.__Duck_IDuck__Dog(t);
            }
            """);

        await test.RunAsync();
    }

    /// <summary>대응하는 멤버가 없으면 호출지점에 에러를 찍는다. 그래야 Strong 덕타이핑이다.</summary>
    [Fact]
    public async Task ReportsMissingMemberAtCallSite()
    {
        var test = Test(/*lang=C#*/"""
            interface IDuck { string Quack(); }
            class Cat { public string Meow() => "meow"; }

            class Use
            {
                static IDuck A() => IDuck.{|DUCK002:From|}(new Cat());
            }
            """);
        test.TestBehaviors = TestBehaviors.SkipGeneratedSourcesCheck;

        await test.RunAsync();
    }

    /// <summary>확장함수로 메꾼 멤버는, 생성코드가 그 네임스페이스를 using 하지 않아도 완전정규화로 불린다.</summary>
    [Fact]
    public async Task FillsMissingMemberWithExtensionMethod()
    {
        var test = Test(/*lang=C#*/"""
            using Helpers;

            interface IDuck { string Quack(); }
            class Cat { public string Meow() => "meow"; }

            namespace Helpers
            {
                static class CatExtensions { public static string Quack(this Cat c) => c.Meow(); }
            }

            class Use
            {
                static IDuck A() => IDuck.From(new Cat());
            }
            """);
        test.TestBehaviors = TestBehaviors.SkipGeneratedSourcesCheck;

        await test.RunAsync();
    }

    /// <summary>C# 인터페이스는 필드를 못 담으니, 소스가 필드로 갖고 있으면 그걸로 잇는다.</summary>
    [Fact]
    public async Task FillsPropertyWithField()
    {
        var test = Test(/*lang=C#*/"""
            interface IName { string Name { get; } }
            class Src { public string Name = "필드"; }

            class Use { static IName A() => IName.From(new Src()); }
            """);
        test.TestBehaviors = TestBehaviors.SkipGeneratedSourcesCheck;

        await test.RunAsync();
    }

    /// <summary>확장 프로퍼티로도 메꿀 수 있다. 정적호출 문법이 없으니 그 네임스페이스를 생성파일에 들여온다.</summary>
    [Fact]
    public async Task FillsPropertyWithExtensionProperty()
    {
        var test = Test(/*lang=C#*/"""
            using Fill;

            interface IName { string Name { get; } }
            class Src { }

            namespace Fill
            {
                static class SrcExtensions { extension(Src s) { public string Name => "확장"; } }
            }

            class Use { static IName A() => IName.From(new Src()); }
            """);
        test.TestBehaviors = TestBehaviors.SkipGeneratedSourcesCheck;

        await test.RunAsync();
    }

    /// <summary>타입이나 접근자가 안 맞으면 생성코드가 아니라 호출지점에서 잡아준다.</summary>
    [Theory]
    [InlineData(/*lang=C#*/"class Src { public int Name => 3; }")]              // 타입 불일치
    [InlineData(/*lang=C#*/"class Src { public string Name => \"읽기만\"; }")]  // set 없음
    public async Task ReportsPropertyMismatchAtCallSite(string src)
    {
        var test = Test($$"""
            interface IName { string Name { get; set; } }
            {{src}}

            class Use { static IName A() => IName.{|DUCK002:From|}(new Src()); }
            """);
        test.TestBehaviors = TestBehaviors.SkipGeneratedSourcesCheck;

        await test.RunAsync();
    }

    static CSharpSourceGeneratorTest<DuckTypeGenerator, DefaultVerifier> Test([StringSyntax("C#")] string code)
    {
        var test = new CSharpSourceGeneratorTest<DuckTypeGenerator, DefaultVerifier> { TestCode = code };
        test.SolutionTransforms.Add((solution, projectId) => solution.WithProjectParseOptions(projectId,
            ((CSharpParseOptions)solution.GetProject(projectId)!.ParseOptions!).WithLanguageVersion(LanguageVersion.Preview)));
        return test;
    }

    static void Expect(CSharpSourceGeneratorTest<DuckTypeGenerator, DefaultVerifier> test, string name, [StringSyntax("C#")] string code)
        => test.TestState.GeneratedSources.Add((typeof(DuckTypeGenerator), name, code));
}
